/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.mk;

import br.com.mk.components.mainPanel.MainPanel;
import br.com.mk.components.optionsPanel.OptionsPanel;
import br.com.mkcomponents.header.Header;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.CornerRadii;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.paint.CycleMethod;
import javafx.scene.paint.LinearGradient;
import javafx.scene.paint.Stop;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start(Stage stage) {
        VBox root = new VBox();
        root.setSpacing(10);

        LinearGradient gradient = new LinearGradient(
                0, 0, 1, 1,         // diagonal 45°
                true,               // coordenadas proporcionais
                CycleMethod.NO_CYCLE,
                new Stop(0, Color.rgb(24, 28, 34)),
                new Stop(0.45, Color.rgb(39, 42, 51)),
                new Stop(1, Color.rgb(0, 0, 0))
        );
        
        Header header = new Header();

        MainPanel mainPanel = new MainPanel();
//      Insets(top, right, bottom, left)
        VBox.setMargin(mainPanel, new Insets(0, 10, 0, 10));


        String[] options = {"Pagar", "Receber", "Pix", "Crédito", "Empréstimo", "Financiamento", "Opções"};
        OptionsPanel optionsPanel = new OptionsPanel(options);

        root.setBackground(new Background(
        		new BackgroundFill(gradient, new CornerRadii(0), Insets.EMPTY)
        		));
        // Adiciona tudo ao root
        root.getChildren().addAll(header, mainPanel, optionsPanel);

        Scene scene = new Scene(root, 650, 270);
        scene.getStylesheets().add("/css/style.css");
        
        stage.setScene(scene);
        stage.setTitle("Painel Conta Bancária");
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}

